
services:

  # PARTIE I : Serveur Web de test (Ubuntu + Apache + PHP 8.3)
  web_server:
    build: .
    container_name: projet_network_security_php
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./html:/var/www/html
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    depends_on:
      database_server:
        condition: service_healthy

  # PARTIE I & II : Serveur de base de données (MariaDB)
  database_server:
    image: mariadb:11.4
    container_name: projet_network_security_mariadb
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PARTIE II : Moteur de supervision Zabbix Server 7.0 LTS
  zabbix_server:
    image: zabbix/zabbix-server-mysql:alpine-7.0-latest
    container_name: projet_network_security_zabbix_server
    ports:
      - "${ZABBIX_PORT}:10051"
    environment:
      - DB_SERVER_HOST=database_server
      - MYSQL_DATABASE=${ZABBIX_DB_NAME}
      - MYSQL_USER=${ZABBIX_DB_USER}
      - MYSQL_PASSWORD=${ZABBIX_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    depends_on:
      database_server:
        condition: service_healthy # Attend que le healthcheck de MySQL soit au vert
    volumes:
      - zabbix_export:/var/lib/zabbix/export

  # PARTIE II : Interface Web officielle de Zabbix 7.0 LTS
  zabbix_frontend:
    image: zabbix/zabbix-web-apache-mysql:alpine-7.0-latest
    container_name: projet_network_security_zabbix_frontend
    ports:
      - "8080:8080" # Acceder à Zabbix sur http://localhost:8080
    environment:
      - DB_SERVER_HOST=database_server
      - MYSQL_DATABASE=${ZABBIX_DB_NAME}
      - MYSQL_USER=${ZABBIX_DB_USER}
      - MYSQL_PASSWORD=${ZABBIX_DB_PASSWORD}
      - ZBX_SERVER_HOST=zabbix_server
      - PHP_TZ=America/Toronto
    depends_on:
      database_server:
        condition: service_healthy
      zabbix_server:
        condition: service_started

  # PARTIE III : Agent Zabbix dédié pour simuler la machine à surveiller
  target_linux_agent:
    image: zabbix/zabbix-agent:alpine-7.0-latest
    container_name: projet_network_security_agent
    environment:
      - ZBX_HOSTNAME=target_linux_machine
      - ZBX_SERVER_HOST=zabbix_server # Autorise ton serveur Zabbix à l'interroger
    depends_on:
      zabbix_server:
        condition: service_started

  # PARTIE IV : Simulation du Routeur Cisco via un démon SNMP
  cisco_router_sim:
    image: alpine:latest
    container_name: cisco_router_sim
    ports:
      - "161:161/udp"
    command: >
      sh -c "apk add --no-cache net-snmp &&
      echo 'rocommunity SNMP' > /etc/snmp/snmpd.conf &&
      echo 'syslocation Salle-Serveurs' >> /etc/snmp/snmpd.conf &&
      echo 'syscontact admin@jarvis.ca' >> /etc/snmp/snmpd.conf &&
      snmpd -f -Lo -c /etc/snmp/snmpd.conf"

volumes:
  mariadb_data:
  zabbix_export:
